# kick: 1

version: 2.1

commands:
  run_tests:
    description: "Build and run tests"
    parameters:
      version:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
          - v1-dependencies-<< parameters.version >>-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
      - run: npm test
jobs:
  node-20:
    docker:
      - image: cimg/node:20.10
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "20"
  node-18:
    docker:
      - image: cimg/node:18.18
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "18"
  node-16:
    docker:
      - image: cimg/node:16.20
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "16"
  node-14:
    docker:
      - image: cimg/node:14.21
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "14"

workflows:
  build:
    jobs:
      - node-20
      - node-18
      - node-16
      - node-14
